# -*- coding: utf-8 -*-
"""superStore Analysis

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Uac_7Wq-l7pPbxoAwO7y0Vo_Ad7JgPMl
"""

import pandas as pd
import numpy as np

data=pd.read_excel('/content/drive/My Drive/Sample-sales-data-excel.xls')

data.head(5)

data['City'].value_counts()



"""# **Displaying** **Data** **Columns**"""

data.columns



"""# **Top** **10** **products** **with** **highest** **profit**"""

product_profit=data.groupby(['Product ID']).sum()

product_profit.head(10)

product_profit=product_profit.loc[:,['Profit','Sales']]
product_profit.head()



"""**Sorting** **to** **Display** **top** **10** **profitable** **products**"""

data2=product_profit.sort_values(['Profit'],ascending=False)
data2.head(10)

data2.head(10).plot(kind='bar')

data2['Profit'].head(10).plot(kind='bar')

"""**Shipment** **Type** **and** **its** **effects** **on** **Profit**"""

shipment_data=data.groupby(['Ship Mode']).sum()
shipment=shipment_data.loc[:,['Sales','Quantity','Profit']]
shipment.sort_values(['Profit'],ascending=False,inplace=True)
shipment.head(10)

shipment['Profit'].head(10).plot(kind='bar')

shipment.plot(kind='bar')

"""# **City** **Wise** **Trend** **of** **Sales**"""

city_data=data.groupby(['City']).sum()
city_data.head(10)

city_data=city_data.loc[:,['Sales','Quantity','Profit']]
city_data.head(10)

city_data.sort_values(['Profit'],ascending=False,inplace=True)
city_data.head(10)

city_data.head(10).plot(kind='bar')

city_data['Profit'].head(10).plot(kind='bar')



"""# **Doing** **analysis** **based** **on** **furnitures**"""

furniture_data=data.groupby(['Category','Sub-Category']).sum()
furniture_data.head(10)

"""# **Grouping** **Category** **and** **Sub** **bold text**-**Category** **Together**"""



furniture_data=furniture_data.loc[:,['Sales','Profit']]
furniture_data.head(10)

furniture_data.sort_values(['Profit'],ascending=False)

furniture_data.head(10).plot(kind='barh')

